- name: enable redis 6.2
  ansible.builtin.command: yum module enable redis:remi-6.2 -y

- name: install redis 
  ansible.builtin.yum:
    name: redis
    state: installed
      
  #allowing the connections from 127.0.0.1 to 0.0.0.0 in /etc/redis.conf
- name: allow remote connections to redis
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
        
- name: start and enable redis
  ansible.builtin.service:
    name: redis
    state: started
    enabled: yes