- name: copy mongo repo to yum.repos.d
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed
    
- name: start and enable mogodb
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes
  
  #replacing the connections from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
- name: enable remote connections to mongodb
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: restart mongodb
  ansible.builtin.service:
    name: mongod
    state: restarted