- name: Install maven
  ansible.builtin.import_role:
    name: common
    tasks_from: maven-setup

- name: SetUp Application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: install dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app  #chdir-->change directory

- name: rename jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app

- name: load mysql schema
  ansible.builtin.import_role:
    name: common
    tasks_from: load-mysql-schema

- name: setup application
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup
