#tasks from catalogue.yaml in ansible-roboshop
#we need to import nodejs.yaml in common(role) --> to this main.yaml in catalogue(role)
  
- name: Install Nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: SetUp Application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: install dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app  #chdir-->change directory

- name: load schema
  ansible.builtin.import_role:
    name: common
    tasks_from: load-mongo-schema

- name: setup application
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup
