- name: install mysql client
  ansible.builtin.yum: 
    name: mysql
    state: installed 
     #execute untill here 

- name: load mysql schema
  ansible.builtin.shell: mysql -h mysql.ops2ai.cloud -uroot -pRoboShop@1 < /app/schema/shipping.sql 